title: Soroush Mirzaei
description: Machine-Learning & Deep-Learning Developer
show_downloads: false
repository_url: https://github.com/soroushmirzaei
theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/soroushmirzaei/telegram-configs-collector
